name: Laravel Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 2
      
      - name: FTP-Deploy-Action
        uses: ephraim/ftp-commit@v1.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/kurnoolbackend/
          protocol: ftps
          exclude: |
            vendor/**
            public/**
          dangerous-clean-slate: false
      
      - name: Install Composer Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader
        working-directory: public_html/kurnoolbackend/

      - name: Run PHP Artisan Commands
        run: |
          php artisan config:cache   # Cache the configuration
          php artisan route:cache     # Cache the routes
          php artisan route:clear   # Clear the route cache
          php artisan optimize     # Optimize
        working-directory: public_html/kurnoolbackend/
